# Generated by Django 4.1.7 on 2023-05-02 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Division', models.CharField(blank=True, max_length=50, null=True)),
                ('Sub_division', models.CharField(blank=True, max_length=50, null=True)),
                ('Zipcode', models.CharField(blank=True, max_length=50, null=True)),
                ('Home_Address', models.CharField(blank=True, max_length=50, null=True)),
                ('Phone', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.customer')),
            ],
        ),
    ]
